---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  when: ansible_os_family == 'Debian'

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    update_cache: yes

- name: Install Docker Engine
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Add user to Docker group using shell
  become: yes
  shell: usermod -aG docker {{ ansible_user }}

- name: Allow user to access docker.sock
  become: yes
  shell: chmod 666 /var/run/docker.sock

- name: Verify user membership in Docker group
  command: groups {{ ansible_user }}
  register: docker
  changed_when: false

- name: Display user groups
  debug:
    var: docker.stdout

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: true

- name: Download Docker Desktop .deb package
  get_url:
    url: "https://desktop.docker.com/linux/main/amd64/docker-desktop-4.10.1-amd64.deb"
    dest: "/tmp/docker-desktop.deb"

- name: Install Docker Desktop
  apt:
    deb: "/tmp/docker-desktop.deb"

- name: Remove the downloaded .deb file
  file:
    path: "/tmp/docker-desktop.deb"
    state: absent