---
- name: Safari - Configure defaults
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ safari.defaults }}"
  tags: safari, defaults
