---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  when: ansible_os_family == 'Debian'

- name: Add Docker’s official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'

- name: Add Docker repository for Raspberry Pi OS (Debian Bookworm)
  ansible.builtin.apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/debian bookworm stable
    state: present
    update_cache: yes

- name: Install Docker Engine
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: true

- name: Verify user membership in Docker group
  command: groups {{ ansible_user }}
  register: docker
  changed_when: false

- name: Display user groups
  debug:
    var: docker.stdout
