---
- name: Install K3s on koden0-3
  hosts: koden0,koden1,koden2,koden3
  become: yes
  vars:
    k3s_version: v1.29.4+k3s1  # adapte la version si besoin
    k3s_install_url: https://get.k3s.io
  tasks:
    - name: Ensure curl is installed
      package:
        name: curl
        state: present

    - name: Install K3s
      shell: |
        curl -sfL {{ k3s_install_url }} | INSTALL_K3S_VERSION={{ k3s_version }} sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s service to be active
      shell: |
        systemctl is-active k3s
      register: k3s_status
      retries: 10
      delay: 5
      until: k3s_status.stdout == 'active'

    - name: Afficher le token de join (pour les workers)
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      when: inventory_hostname == 'koden0'  # master node

    - name: Afficher l'IP du master (pour join)
      ansible.builtin.command: hostname -I
      register: master_ip
      when: inventory_hostname == 'koden0'

    - name: Afficher instructions de join pour les workers
      debug:
        msg: "Sur les workers, exécutez : curl -sfL {{ k3s_install_url }} | K3S_URL=https://{{ hostvars['koden0'].master_ip.stdout.split()[0] }}:6443 K3S_TOKEN={{ hostvars['koden0'].k3s_token.stdout }} sh -"
      when: inventory_hostname == 'koden0'

    - name: Join cluster (workers)
      shell: |
        curl -sfL {{ k3s_install_url }} | K3S_URL=https://{{ hostvars['koden0'].master_ip.stdout.split()[0] }}:6443 K3S_TOKEN={{ hostvars['koden0'].k3s_token.stdout }} sh -
      when: inventory_hostname != 'koden0'
      args:
        creates: /usr/local/bin/k3s-agent

