---
- name: Cleanup Kubernetes (kubeadm/kubelet/kubectl/CNI) on koden0-3
  hosts: koden0,koden1,koden2,koden3
  become: yes
  tasks:
    - name: Stop kubelet service
      service:
        name: kubelet
        state: stopped
      ignore_errors: yes

    - name: Reset kubeadm (if present)
      command: kubeadm reset -f
      ignore_errors: yes

    - name: Remove Kubernetes packages
      package:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: absent
      ignore_errors: yes

    - name: Remove CNI plugins
      file:
        path: /opt/cni/bin
        state: absent
      ignore_errors: yes

    - name: Remove Kubernetes config directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/kubernetes
        - /var/lib/etcd
        - /var/lib/kubelet
        - /etc/cni
        - /var/lib/cni
        - /root/.kube
        - /home/{{ ansible_user }}/.kube
      ignore_errors: yes

    - name: Remove kubeadm join command file
      file:
        path: /tmp/kubeadm_join_cmd.sh
        state: absent
      ignore_errors: yes

    - name: Remove Calico manifests
      file:
        path: /etc/cni/net.d
        state: absent
      ignore_errors: yes

    - name: Remove any leftover Docker containers (if used)
      shell: |
        docker rm -f $(docker ps -aq)
      ignore_errors: yes
      when: ansible_facts.packages['docker'] is defined

    - name: Remove any leftover containerd containers (if used)
      shell: |
        crictl rm -f $(crictl ps -aq)
      ignore_errors: yes
      when: ansible_facts.packages['containerd'] is defined

    - name: Clean iptables rules
      shell: |
        iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
      ignore_errors: yes

    - name: Reboot node (optional, uncomment if needed)
      # reboot:
      #   msg: "Rebooting after Kubernetes cleanup"
      #   pre_reboot_delay: 5
      debug:
        msg: "Cleanup complete. Reboot if needed."

