---
# Playbook to deploy a Kubernetes cluster on 4 identical mini-PCs
# This playbook will:
# 1. Set up all nodes with prerequisites
# 2. Configure the first node as the control plane (master)
# 3. Join the other nodes as workers

# First, define host groups for control plane and workers
- name: Update inventory with control plane and worker groups
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add host groups
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        ansible_host: "{{ hostvars[item.name]['ansible_host'] }}"
        ansible_user: "{{ hostvars[item.name]['ansible_user'] }}"
      loop:
        - { name: "koden0", groups: "k8s_control_plane" }
        - { name: "koden1", groups: "k8s_workers" }
        - { name: "koden2", groups: "k8s_workers" }
        - { name: "koden3", groups: "k8s_workers" }

# Common setup for all nodes
- name: Common Kubernetes setup for all nodes
  hosts: k8s_nodes
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present

    - name: Disable swap
      shell: swapoff -a
      changed_when: false

    - name: Remove swap from fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: Load required kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Set up kernel modules to load at boot
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        mode: '0644'

    - name: Set up kernel parameters for Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
        mode: '0644'

    - name: Apply sysctl parameters
      command: sysctl --system
      changed_when: false

    # Install containerd
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install containerd
      apt:
        name: containerd.io
        state: present
        update_cache: yes

    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Configure containerd
      shell: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Update containerd configuration to use systemd cgroup driver
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes
        daemon_reload: yes

    # Install Kubernetes components
    - name: Add Kubernetes GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        filename: kubernetes

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages at their installed version
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable kubelet service
      systemd:
        name: kubelet
        enabled: yes

# Initialize the control plane
- name: Initialize Kubernetes control plane
  hosts: k8s_control_plane
  become: true
  tasks:
    - name: Initialize the Kubernetes cluster using kubeadm
      command: >
        kubeadm init --pod-network-cidr=192.168.0.0/16
        --apiserver-advertise-address={{ ansible_host }}
      register: kubeadm_init
      changed_when: kubeadm_init.rc == 0
      failed_when: kubeadm_init.rc != 0 and "already exists" not in kubeadm_init.stderr

    - name: Create .kube directory for the user
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Install Calico network plugin
      become: false
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      changed_when: false

    - name: Generate join command for worker nodes
      command: kubeadm token create --print-join-command
      register: join_command
      changed_when: false

    - name: Store join command
      set_fact:
        join_command: "{{ join_command.stdout }}"

    - name: Copy join command to local file
      local_action:
        module: copy
        content: "{{ join_command }}"
        dest: "/tmp/k8s_join_command"
        mode: '0644'
      become: false

# Join worker nodes to the cluster
- name: Join worker nodes to the Kubernetes cluster
  hosts: k8s_workers
  become: true
  tasks:
    - name: Copy join command from local file
      copy:
        src: /tmp/k8s_join_command
        dest: /tmp/k8s_join_command
        mode: '0644'

    - name: Join the Kubernetes cluster
      command: sh /tmp/k8s_join_command
      register: join_result
      changed_when: join_result.rc == 0
      failed_when: join_result.rc != 0 and "already exists" not in join_result.stderr

    - name: Remove join command file
      file:
        path: /tmp/k8s_join_command
        state: absent

# Verify the cluster
- name: Verify Kubernetes cluster
  hosts: k8s_control_plane
  become: false
  tasks:
    - name: Wait for all nodes to be ready
      command: kubectl wait --for=condition=Ready nodes --all --timeout=300s
      register: nodes_ready
      changed_when: false
      failed_when: false

    - name: Get cluster status
      command: kubectl get nodes -o wide
      register: cluster_status
      changed_when: false

    - name: Display cluster status
      debug:
        var: cluster_status.stdout_lines