---
- name: Install necessary zsh homebrew packages
  community.general.homebrew:
    name:
      - zsh
      - zsh-completions
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present
  tags: zsh

- name: Check for .oh-my-zsh exists
  ansible.builtin.stat:
    path: /Users/{{ username }}/.oh-my-zsh
  register: ohmyzsh_folder
  tags: zsh

- name: Install Oh My Zsh
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL {{ ohmyzsh.url }})"
  when: not ohmyzsh_folder.stat.exists
  changed_when: true
  tags: zsh

- name: Install powerlevel10k theme
  ansible.builtin.git:
    repo: "{{ powerlevel10k.theme.url }}"
    dest: "/Users/{{ username }}/.oh-my-zsh/custom/themes/powerlevel10k"
    version: "{{ powerlevel10k.theme.version }}"
  tags: zsh

- name: Copy zsh configuration files
  tags: zsh
  block:
    - name: Copy .zshrc
      ansible.builtin.template:
        src: "zsh/{{ item }}.j2"
        dest: "/Users/{{ username }}/{{ item }}"
        mode: "0644"
      loop:
        - .zshrc

    - name: Copy .p10k.zsh and .fzf.zsh
      ansible.builtin.copy:
        src: "zsh/{{ item }}"
        dest: "/Users/{{ username }}/{{ item }}"
        mode: "0644"
      loop:
        - .p10k.zsh
        - .fzf.zsh

- name: Set default shell
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh
  become: true
