---
- name: List contents of the extensions directory
  command: ls -la ~/.local/share/gnome-shell/extensions/
  register: ls_output
  become_user: "{{ ansible_user }}"

- name: Output result of ls
  debug:
    msg: "{{ ls_output.stdout_lines }}"

- name: Clone GNOME Shell extension repository
  git:
    repo: "https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator.git"
    dest: "~/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com"
    clone: yes
    update: yes
  become_user: "{{ ansible_user }}"  # Ensure it clones under the user, not root

- name: Enable GNOME Shell extension
  shell: gnome-extensions enable "clipboard-indicator@tudmotu.com"
  become_user: "{{ ansible_user }}"  # Run as user to affect user session