---
# Update all packages to the latest version
- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Upgrade all packages
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian"

# Ensure basic utilities are installed
- name: Ensure necessary packages are installed
  package:
    name:
      - vim
      - curl
      - git
      - tree
      - gnome-shell-extensions
      - python3-pip
    state: present

#- name: Install gnome-shell-extensions clipboard Indicator
#  include_tasks: install_extensions_clipboard_indicator.yml

- name: Install Google Chrome
  include_tasks: install_chrome.yml