- name: Create a symbolic link for airport command
  ansible.builtin.file:
    src: /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport
    dest: /usr/local/bin/airport
    state: link
  become: true
  tags: tmux

- name: Add binary scripts for bottom bar
  ansible.builtin.copy:
    src: tmux/bin/
    dest: "/Users/{{ username }}/bin"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0755"
  tags: tmux